### ISSUE TITLE
Entering negative numbers in the inputs

### ISSUE THREAD

**Issue by germmand** [germmand/spend-jeff-bezos-money#3]
**Current behavior:**
When there's a number (different from zero) in any of the input components, you can turn it negative by adding a minus (`-`) at the beginning. You can't do it if the input has a value of zero.

**Expected behavior:**
You shouldn't be able to add negatives to the input components.

**Comment by ocarlic** [comment]
I added PR to this issue [#9 ](https://github.com/germmand/spend-jeff-bezos-money/pull/9)
